--TẠO DATABASE
create database DATHANG
--TAO BẢNG
IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHANG
GO
CREATE TABLE KHACHANG (
MAKH VARCHAR(20) NOT NULL,
TENKH NVARCHAR(50) NULL,
TAIKHOAN VARCHAR(30) NULL,
CONSTRAINT PK_KHACHNANG PRIMARY KEY (MAKH)
)

IF OBJECT_ID('DATHANG') IS NOT NULL
DROP TABLE DATHANG
GO
CREATE TABLE DATHANG(
MADATHANG VARCHAR(10) NOT NULL,
MAKH VARCHAR(20) NULL,
MASACH VARCHAR(20) NULL,
SOLUONG INT NULL,
DONGIA MONEY NULL,
CONSTRAINT PK_DATHANG PRIMARY KEY(MADATHANG),
CONSTRAINT FK_DATHANG_KHACHANG FOREIGN KEY (MAKH) REFERENCES KHACHANG(MAKH)
)
--NHAP
DELETE FROM KHACHANG
INSERT INTO KHACHANG VALUES 
('A01',N'ToanNK','000502001'),
('A02',N'VanNT','000745001'),
('A03',N'TrangTT','000341928')

DELETE FROM DATHANG
INSERT INTO DATHANG VALUES 
('DT01','A01','S01',10,50000),
('DT02','A01','S02',9,30000),
('DT03','A02','S03',7,70000)

SELECT * FROM KHACHANG
SELECT * FROM DATHANG ORDER BY SOLUONG ASC

--CÂU 1
SELECT MAKH,TENKH FROM KHACHANG
--CÂU 2
SELECT MADATHANG,MAKH,SOLUONG,DONGIA,(SOLUONG*DONGIA) AS THANHTIEN FROM DATHANG
--CÂU 3
SELECT * FROM KHACHANG WHERE TAIKHOAN LIKE '%01' 
--CÂU 4
SELECT * FROM KHACHANG WHERE TENKH LIKE N'T%' 
--CÂU 5
SELECT MAKH,SUM(SOLUONG) AS TONGSO FROM DATHANG GROUP BY MAKH HAVING SUM(SOLUONG) >=10 ORDER BY SUM(SOLUONG) ASC
--CÂU 6
SELECT TOP 1 MAKH,SOLUONG FROM DATHANG ORDER BY SOLUONG DESC
---CÂU 6 CÁCH 2 SO SÁNH TỔNG SỐ SẢN PHẨM MÀ 1 KHÁC HÀNG MUA RỒI SO SÁNH LẤY KHÁCH HÀNG TOP 1
SELECT TOP 1 MAKH,SUM(SOLUONG) AS TONGSO FROM DATHANG GROUP BY MAKH ORDER BY SUM(SOLUONG) DESC 

---group by MỚI DÙNG ĐUỌC HAVING GROUP BY NHÓM NHỮNG CÁI CHUNG LẠI VỚI NHAU
SELECT SUM(SOLUONG) FROM  DATHANG GROUP BY MAKH