use QLBH;

if OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
GO
CREATE TABLE KHACHHANG
(
MAKHACHHANG TEXT,
HOVATEN TEXT,
TEN TEXT,
)



if OBJECT_ID('HOADON') IS NOT NULL
DROP TABLE HOADON
GO
CREATE TABLE HOADON 
(
MAHD NVARCHAR(10) NOT NULL,
NGAYMUA DATETIME NULL,
MAKH NVARCHAR(10) NULL,
TRANGTHAI NVARCHAR(50) NULL,
CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG 
)
IF OBJECT_ID('HOADONCT') IS NOT NULL
DROP TABLE HOADONCT
GO 
CREATE TABLE HOADONCT
(
MAHD  NVARCHAR(10) NOT NULL
MASP NVARCHAR(10) NOT NULL,
SLBAN INT NULL,
CONSTRAIN FK_HOADONCT_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON,
CONSTRAIN FK_HOADONCT_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM,
CONSTRAIN PK_HOADONCT PRIMARY KEY (MAHD,MASP)
)